const playersData = {
  "Atlanta Hawks": [
    {"name": "Trae Young", "position": "PG", "careerGames": 400, "careerPPG": 25.8, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Clint Capela", "position": "C", "careerGames": 650, "careerPPG": 12.5, "draftRound": 1, "allStarAppearances": 0},
    {"name": "De'Andre Hunter", "position": "SF", "careerGames": 250, "careerPPG": 9.2, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Bogdan Bogdanovic", "position": "SG", "careerGames": 500, "careerPPG": 13.2, "draftRound": 2, "allStarAppearances": 0},
    {"name": "Dominique Wilkins", "position": "SF", "careerGames": 1074, "careerPPG": 24.8, "draftRound": 1, "allStarAppearances": 9},
    {"name": "Bob Pettit", "position": "PF", "careerGames": 792, "careerPPG": 26.4, "draftRound": 1, "allStarAppearances": 12},
    {"name": "Dikembe Mutombo", "position": "C", "careerGames": 1105, "careerPPG": 9.8, "draftRound": 1, "allStarAppearances": 8},
    {"name": "Josh Smith", "position": "PF", "careerGames": 1015, "careerPPG": 13.0, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Al Horford", "position": "C", "careerGames": 1100, "careerPPG": 14.2, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Lou Williams", "position": "SG", "careerGames": 850, "careerPPG": 16.5, "draftRound": 2, "allStarAppearances": 0},
    {"name": "Shareef Abdur-Rahim", "position": "PF", "careerGames": 976, "careerPPG": 20.1, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Jason Terry", "position": "SG", "careerGames": 1410, "careerPPG": 14.7, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Marvin Williams", "position": "PF", "careerGames": 1030, "careerPPG": 12.6, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Zeke Nnaji", "position": "PF", "careerGames": 150, "careerPPG": 8.1, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Jon Koncak", "position": "C", "careerGames": 520, "careerPPG": 8.3, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Rudy Gay", "position": "SF", "careerGames": 1150, "careerPPG": 16.1, "draftRound": 1, "allStarAppearances": 0}
  ],
  "Boston Celtics": [
    {"name": "Jayson Tatum", "position": "SF", "careerGames": 450, "careerPPG": 28.1, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Jaylen Brown", "position": "SF", "careerGames": 400, "careerPPG": 23.5, "draftRound": 1, "allStarAppearances": 2},
    {"name": "Derrick White", "position": "PG", "careerGames": 500, "careerPPG": 10.7, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Larry Bird", "position": "SF", "careerGames": 897, "careerPPG": 24.3, "draftRound": 1, "allStarAppearances": 12},
    {"name": "Bill Russell", "position": "C", "careerGames": 963, "careerPPG": 15.1, "draftRound": 1, "allStarAppearances": 12},
    {"name": "John Havlicek", "position": "SG", "careerGames": 1270, "careerPPG": 20.8, "draftRound": 1, "allStarAppearances": 11},
    {"name": "Paul Pierce", "position": "SF", "careerGames": 1344, "careerPPG": 19.7, "draftRound": 1, "allStarAppearances": 10},
    {"name": "Kevin Garnett", "position": "PF", "careerGames": 1462, "careerPPG": 17.8, "draftRound": 1, "allStarAppearances": 15},
    {"name": "Sam Jones", "position": "SG", "careerGames": 871, "careerPPG": 17.7, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Tom Heinsohn", "position": "PF", "careerGames": 654, "careerPPG": 18.6, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Rajon Rondo", "position": "PG", "careerGames": 1100, "careerPPG": 10.2, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Dennis Johnson", "position": "PG", "careerGames": 1100, "careerPPG": 13.0, "draftRound": 2, "allStarAppearances": 3},
    {"name": "Danny Ainge", "position": "SG", "careerGames": 1042, "careerPPG": 11.2, "draftRound": 1, "allStarAppearances": 2},
    {"name": "Bailey Howell", "position": "PF", "careerGames": 1030, "careerPPG": 15.0, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Robert Parish", "position": "C", "careerGames": 1611, "careerPPG": 14.5, "draftRound": 1, "allStarAppearances": 9}
  ],
  "Brooklyn Nets": [
    {"name": "Mikal Bridges", "position": "SF", "careerGames": 500, "careerPPG": 15.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Cameron Johnson", "position": "SG", "careerGames": 400, "careerPPG": 14.2, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Spencer Dinwiddie", "position": "PG", "careerGames": 650, "careerPPG": 12.8, "draftRound": 2, "allStarAppearances": 0},
    {"name": "Kyrie Irving", "position": "PG", "careerGames": 800, "careerPPG": 23.4, "draftRound": 1, "allStarAppearances": 11},
    {"name": "Vince Carter", "position": "SG", "careerGames": 1541, "careerPPG": 19.5, "draftRound": 1, "allStarAppearances": 8},
    {"name": "Jason Kidd", "position": "PG", "careerGames": 1391, "careerPPG": 12.6, "draftRound": 1, "allStarAppearances": 10},
    {"name": "Kenyon Martin", "position": "PF", "careerGames": 989, "careerPPG": 13.5, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Richard Jefferson", "position": "SF", "careerGames": 1079, "careerPPG": 12.0, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Marcus Williams", "position": "SG", "careerGames": 450, "careerPPG": 8.2, "draftRound": 2, "allStarAppearances": 0},
    {"name": "Antoine Wright", "position": "SF", "careerGames": 350, "careerPPG": 5.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Trenton Hassell", "position": "SF", "careerGames": 680, "careerPPG": 7.5, "draftRound": 2, "allStarAppearances": 0},
    {"name": "Devin Harris", "position": "PG", "careerGames": 900, "careerPPG": 10.5, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Terrence Williams", "position": "SG", "careerGames": 400, "careerPPG": 6.8, "draftRound": 1, "allStarAppearances": 0}
  ],
  "Charlotte Hornets": [
    {"name": "LaMelo Ball", "position": "PG", "careerGames": 300, "careerPPG": 20.3, "draftRound": 1, "allStarAppearances": 0},
    {"name": "P.J. Washington", "position": "PF", "careerGames": 400, "careerPPG": 15.7, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Miles Bridges", "position": "SF", "careerGames": 450, "careerPPG": 17.2, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Kemba Walker", "position": "PG", "careerGames": 1043, "careerPPG": 19.1, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Marvin Williams", "position": "PF", "careerGames": 400, "careerPPG": 11.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Gerald Wallace", "position": "SF", "careerGames": 1088, "careerPPG": 13.1, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Cody Zeller", "position": "C", "careerGames": 500, "careerPPG": 10.1, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Michael Kidd-Gilchrist", "position": "SF", "careerGames": 600, "careerPPG": 9.5, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Bismack Biyombo", "position": "C", "careerGames": 700, "careerPPG": 5.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Tyrus Thomas", "position": "PF", "careerGames": 600, "careerPPG": 10.2, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Brendan Haywood", "position": "C", "careerGames": 880, "careerPPG": 6.9, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Sean May", "position": "PF", "careerGames": 300, "careerPPG": 8.5, "draftRound": 1, "allStarAppearances": 0}
  ],
  "Chicago Bulls": [
    {"name": "Michael Jordan", "position": "SG", "careerGames": 1072, "careerPPG": 30.1, "draftRound": 1, "allStarAppearances": 14},
    {"name": "Scottie Pippen", "position": "SF", "careerGames": 1178, "careerPPG": 16.1, "draftRound": 1, "allStarAppearances": 8},
    {"name": "Dennis Rodman", "position": "PF", "careerGames": 911, "careerPPG": 7.3, "draftRound": 2, "allStarAppearances": 8},
    {"name": "DeMar DeRozan", "position": "SG", "careerGames": 800, "careerPPG": 20.9, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Nikola Vucevic", "position": "C", "careerGames": 900, "careerPPG": 14.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Derrick Rose", "position": "PG", "careerGames": 800, "careerPPG": 17.4, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Joakim Noah", "position": "C", "careerGames": 842, "careerPPG": 9.4, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Pau Gasol", "position": "C", "careerGames": 1000, "careerPPG": 17.0, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Horace Grant", "position": "PF", "careerGames": 1199, "careerPPG": 9.9, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Bob Love", "position": "SF", "careerGames": 1011, "careerPPG": 21.0, "draftRound": 1, "allStarAppearances": 8},
    {"name": "Jerry Sloan", "position": "SG", "careerGames": 755, "careerPPG": 14.0, "draftRound": 2, "allStarAppearances": 1},
    {"name": "Tony Kukoc", "position": "SF", "careerGames": 806, "careerPPG": 12.7, "draftRound": 1, "allStarAppearances": 2},
    {"name": "B.J. Armstrong", "position": "PG", "careerGames": 875, "careerPPG": 8.6, "draftRound": 1, "allStarAppearances": 1}
  ],
  "Cleveland Cavaliers": [
    {"name": "LeBron James", "position": "SF", "careerGames": 1410, "careerPPG": 27.2, "draftRound": 1, "allStarAppearances": 19},
    {"name": "Kyrie Irving", "position": "PG", "careerGames": 600, "careerPPG": 23.8, "draftRound": 1, "allStarAppearances": 11},
    {"name": "Kevin Love", "position": "PF", "careerGames": 1100, "careerPPG": 17.6, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Mark Price", "position": "PG", "careerGames": 728, "careerPPG": 15.2, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Zydrunas Ilgauskas", "position": "C", "careerGames": 916, "careerPPG": 13.6, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Anderson Varejao", "position": "C", "careerGames": 872, "careerPPG": 10.2, "draftRound": 2, "allStarAppearances": 0},
    {"name": "Larry Nance Jr.", "position": "PF", "careerGames": 600, "careerPPG": 10.1, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Darius Garland", "position": "PG", "careerGames": 350, "careerPPG": 18.1, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Evan Mobley", "position": "PF", "careerGames": 250, "careerPPG": 15.2, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Dan Majerle", "position": "SG", "careerGames": 1003, "careerPPG": 11.6, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Cedi Osman", "position": "SF", "careerGames": 500, "careerPPG": 10.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Jeff Green", "position": "PF", "careerGames": 1000, "careerPPG": 9.5, "draftRound": 1, "allStarAppearances": 0}
  ],
  "Dallas Mavericks": [
    {"name": "Luka Doncic", "position": "PG", "careerGames": 400, "careerPPG": 32.8, "draftRound": 1, "allStarAppearances": 8},
    {"name": "Kyrie Irving", "position": "PG", "careerGames": 200, "careerPPG": 26.3, "draftRound": 1, "allStarAppearances": 11},
    {"name": "Dirk Nowitzki", "position": "PF", "careerGames": 1522, "careerPPG": 20.7, "draftRound": 1, "allStarAppearances": 14},
    {"name": "Jason Kidd", "position": "PG", "careerGames": 650, "careerPPG": 13.5, "draftRound": 1, "allStarAppearances": 10},
    {"name": "Steve Nash", "position": "PG", "careerGames": 784, "careerPPG": 14.5, "draftRound": 1, "allStarAppearances": 8},
    {"name": "Devin Harris", "position": "PG", "careerGames": 450, "careerPPG": 11.2, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Christian Wood", "position": "C", "careerGames": 350, "careerPPG": 12.3, "draftRound": 2, "allStarAppearances": 0},
    {"name": "Spencer Dinwiddie", "position": "PG", "careerGames": 250, "careerPPG": 14.1, "draftRound": 2, "allStarAppearances": 0},
    {"name": "Josh Howard", "position": "SF", "careerGames": 800, "careerPPG": 13.6, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Shawn Marion", "position": "SF", "careerGames": 450, "careerPPG": 14.8, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Rajon Rondo", "position": "PG", "careerGames": 200, "careerPPG": 9.2, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Rolando Blackman", "position": "SG", "careerGames": 1087, "careerPPG": 18.0, "draftRound": 1, "allStarAppearances": 1}
  ],
  "Denver Nuggets": [
    {"name": "Nikola Jokic", "position": "C", "careerGames": 650, "careerPPG": 25.9, "draftRound": 1, "allStarAppearances": 7},
    {"name": "Jamal Murray", "position": "PG", "careerGames": 550, "careerPPG": 20.4, "draftRound": 1, "allStarAppearances": 2},
    {"name": "Kawhi Leonard", "position": "SF", "careerGames": 250, "careerPPG": 27.1, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Karl-Anthony Towns", "position": "C", "careerGames": 200, "careerPPG": 21.8, "draftRound": 1, "allStarAppearances": 3},
    {"name": "Alex English", "position": "SF", "careerGames": 1193, "careerPPG": 21.1, "draftRound": 2, "allStarAppearances": 8},
    {"name": "David Thompson", "position": "SG", "careerGames": 509, "careerPPG": 24.1, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Dan Issel", "position": "C", "careerGames": 718, "careerPPG": 25.8, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Dikembe Mutombo", "position": "C", "careerGames": 400, "careerPPG": 12.5, "draftRound": 1, "allStarAppearances": 8},
    {"name": "Andre Miller", "position": "PG", "careerGames": 1200, "careerPPG": 10.9, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Voshon Lenard", "position": "SG", "careerGames": 600, "careerPPG": 9.8, "draftRound": 2, "allStarAppearances": 0},
    {"name": "Jalen Murray", "position": "SF", "careerGames": 350, "careerPPG": 12.1, "draftRound": 1, "allStarAppearances": 0}
  ],
  "Detroit Pistons": [
    {"name": "Isiah Thomas", "position": "PG", "careerGames": 979, "careerPPG": 20.1, "draftRound": 1, "allStarAppearances": 12},
    {"name": "Joe Dumars", "position": "SG", "careerGames": 1001, "careerPPG": 16.1, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Dennis Rodman", "position": "PF", "careerGames": 500, "careerPPG": 6.8, "draftRound": 2, "allStarAppearances": 8},
    {"name": "Bill Laimbeer", "position": "C", "careerGames": 937, "careerPPG": 12.9, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Bob McAdoo", "position": "PF", "careerGames": 852, "careerPPG": 22.1, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Grant Hill", "position": "SF", "careerGames": 1026, "careerPPG": 17.4, "draftRound": 1, "allStarAppearances": 7},
    {"name": "Andre Drummond", "position": "C", "careerGames": 800, "careerPPG": 13.5, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Reggie Jackson", "position": "PG", "careerGames": 750, "careerPPG": 13.7, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Rasheed Wallace", "position": "PF", "careerGames": 1099, "careerPPG": 16.3, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Saddiq Bey", "position": "SF", "careerGames": 300, "careerPPG": 14.5, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Monte Towe", "position": "PG", "careerGames": 400, "careerPPG": 5.2, "draftRound": 1, "allStarAppearances": 0}
  ],
  "Golden State Warriors": [
    {"name": "Stephen Curry", "position": "PG", "careerGames": 1000, "careerPPG": 28.3, "draftRound": 1, "allStarAppearances": 10},
    {"name": "Klay Thompson", "position": "SG", "careerGames": 900, "careerPPG": 19.5, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Draymond Green", "position": "PF", "careerGames": 1000, "careerPPG": 9.5, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Wilt Chamberlain", "position": "C", "careerGames": 1045, "careerPPG": 30.1, "draftRound": 1, "allStarAppearances": 13},
    {"name": "Rick Barry", "position": "SF", "careerGames": 1020, "careerPPG": 23.2, "draftRound": 1, "allStarAppearances": 12},
    {"name": "Gail Goodrich", "position": "SG", "careerGames": 800, "careerPPG": 18.6, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Nate Thurmond", "position": "C", "careerGames": 964, "careerPPG": 15.0, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Andrew Wiggins", "position": "SF", "careerGames": 700, "careerPPG": 17.1, "draftRound": 1, "allStarAppearances": 2},
    {"name": "Chris Mullin", "position": "SF", "careerGames": 986, "careerPPG": 17.9, "draftRound": 1, "allStarAppearances": 2},
    {"name": "Jeff Mullins", "position": "SG", "careerGames": 810, "careerPPG": 15.4, "draftRound": 1, "allStarAppearances": 3},
    {"name": "Al Attles", "position": "SG", "careerGames": 711, "careerPPG": 9.2, "draftRound": 1, "allStarAppearances": 0}
  ],
  "Houston Rockets": [
    {"name": "Moses Malone", "position": "C", "careerGames": 1329, "careerPPG": 22.8, "draftRound": 1, "allStarAppearances": 12},
    {"name": "Hakeem Olajuwon", "position": "C", "careerGames": 1238, "careerPPG": 21.8, "draftRound": 1, "allStarAppearances": 12},
    {"name": "James Harden", "position": "SG", "careerGames": 900, "careerPPG": 25.8, "draftRound": 1, "allStarAppearances": 11},
    {"name": "Ralph Sampson", "position": "C", "careerGames": 556, "careerPPG": 15.4, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Calvin Murphy", "position": "PG", "careerGames": 1002, "careerPPG": 17.9, "draftRound": 2, "allStarAppearances": 1},
    {"name": "Rudy Tomjanovich", "position": "PF", "careerGames": 768, "careerPPG": 15.3, "draftRound": 1, "allStarAppearances": 2},
    {"name": "Bob McAdoo", "position": "C", "careerGames": 300, "careerPPG": 19.8, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Steve Francis", "position": "PG", "careerGames": 803, "careerPPG": 20.1, "draftRound": 1, "allStarAppearances": 3},
    {"name": "Tracy McGrady", "position": "SG", "careerGames": 500, "careerPPG": 19.1, "draftRound": 1, "allStarAppearances": 7},
    {"name": "Scottie Barnes", "position": "PF", "careerGames": 400, "careerPPG": 12.5, "draftRound": 1, "allStarAppearances": 0}
  ],
  "Los Angeles Clippers": [
    {"name": "Kawhi Leonard", "position": "SF", "careerGames": 700, "careerPPG": 24.8, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Paul George", "position": "SF", "careerGames": 900, "careerPPG": 18.5, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Blake Griffin", "position": "PF", "careerGames": 901, "careerPPG": 21.9, "draftRound": 1, "allStarAppearances": 6},
    {"name": "DeAndre Jordan", "position": "C", "careerGames": 900, "careerPPG": 11.2, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Chris Paul", "position": "PG", "careerGames": 1050, "careerPPG": 17.7, "draftRound": 1, "allStarAppearances": 11},
    {"name": "Elton Brand", "position": "C", "careerGames": 999, "careerPPG": 17.1, "draftRound": 1, "allStarAppearances": 2},
    {"name": "Corey Maggette", "position": "SG", "careerGames": 1048, "careerPPG": 16.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Randy Foye", "position": "PG", "careerGames": 900, "careerPPG": 11.5, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Norm Powell", "position": "SG", "careerGames": 700, "careerPPG": 12.3, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Cuttino Mobley", "position": "SG", "careerGames": 821, "careerPPG": 16.7, "draftRound": 1, "allStarAppearances": 0}
  ],
  "Los Angeles Lakers": [
    {"name": "LeBron James", "position": "SF", "careerGames": 1410, "careerPPG": 27.2, "draftRound": 1, "allStarAppearances": 19},
    {"name": "Kareem Abdul-Jabbar", "position": "C", "careerGames": 1560, "careerPPG": 24.6, "draftRound": 1, "allStarAppearances": 19},
    {"name": "Magic Johnson", "position": "PG", "careerGames": 906, "careerPPG": 19.5, "draftRound": 1, "allStarAppearances": 12},
    {"name": "Shaquille O'Neal", "position": "C", "careerGames": 1207, "careerPPG": 23.4, "draftRound": 1, "allStarAppearances": 15},
    {"name": "Kobe Bryant", "position": "SG", "careerGames": 1346, "careerPPG": 25.0, "draftRound": 1, "allStarAppearances": 18},
    {"name": "Pau Gasol", "position": "C", "careerGames": 800, "careerPPG": 18.2, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Jerry West", "position": "SG", "careerGames": 932, "careerPPG": 27.0, "draftRound": 1, "allStarAppearances": 14},
    {"name": "Wilt Chamberlain", "position": "C", "careerGames": 160, "careerPPG": 28.8, "draftRound": 1, "allStarAppearances": 13},
    {"name": "Elgin Baylor", "position": "SF", "careerGames": 846, "careerPPG": 27.4, "draftRound": 1, "allStarAppearances": 11},
    {"name": "James Worthy", "position": "SF", "careerGames": 926, "careerPPG": 17.6, "draftRound": 1, "allStarAppearances": 7},
    {"name": "Pau Gasol", "position": "C", "careerGames": 300, "careerPPG": 16.5, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Anthony Davis", "position": "PF", "careerGames": 750, "careerPPG": 24.3, "draftRound": 1, "allStarAppearances": 8}
  ],
  "Memphis Grizzlies": [
    {"name": "Ja Morant", "position": "PG", "careerGames": 400, "careerPPG": 23.3, "draftRound": 1, "allStarAppearances": 3},
    {"name": "Brandon Clarke", "position": "PF", "careerGames": 350, "careerPPG": 12.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Desmond Bane", "position": "SG", "careerGames": 350, "careerPPG": 16.2, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Marc Gasol", "position": "C", "careerGames": 1002, "careerPPG": 14.0, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Pau Gasol", "position": "C", "careerGames": 500, "careerPPG": 19.2, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Zach Randolph", "position": "PF", "careerGames": 1189, "careerPPG": 18.1, "draftRound": 1, "allStarAppearances": 2},
    {"name": "Tony Allen", "position": "SG", "careerGames": 1001, "careerPPG": 10.6, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Mike Conley", "position": "PG", "careerGames": 1000, "careerPPG": 11.2, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Tyreke Evans", "position": "PG", "careerGames": 600, "careerPPG": 12.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Rudy Gay", "position": "SF", "careerGames": 700, "careerPPG": 17.6, "draftRound": 1, "allStarAppearances": 0}
  ],
  "Miami Heat": [
    {"name": "Dwyane Wade", "position": "SG", "careerGames": 1054, "careerPPG": 22.0, "draftRound": 1, "allStarAppearances": 13},
    {"name": "LeBron James", "position": "SF", "careerGames": 294, "careerPPG": 27.1, "draftRound": 1, "allStarAppearances": 19},
    {"name": "Chris Bosh", "position": "C", "careerGames": 900, "careerPPG": 19.1, "draftRound": 1, "allStarAppearances": 11},
    {"name": "Alonzo Mourning", "position": "C", "careerGames": 927, "careerPPG": 17.1, "draftRound": 1, "allStarAppearances": 7},
    {"name": "Tim Hardaway", "position": "PG", "careerGames": 867, "careerPPG": 18.2, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Jamal Murray", "position": "SG", "careerGames": 250, "careerPPG": 18.5, "draftRound": 1, "allStarAppearances": 2},
    {"name": "Bam Adebayo", "position": "C", "careerGames": 500, "careerPPG": 15.9, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Jimmy Butler", "position": "SF", "careerGames": 800, "careerPPG": 18.7, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Goran Dragic", "position": "PG", "careerGames": 900, "careerPPG": 11.1, "draftRound": 2, "allStarAppearances": 0},
    {"name": "Eddie Jones", "position": "SG", "careerGames": 900, "careerPPG": 15.6, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Anthony Carter", "position": "PG", "careerGames": 400, "careerPPG": 3.8, "draftRound": 2, "allStarAppearances": 0}
  ],
  "Milwaukee Bucks": [
    {"name": "Giannis Antetokounmpo", "position": "PF", "careerGames": 850, "careerPPG": 27.8, "draftRound": 1, "allStarAppearances": 10},
    {"name": "Damian Lillard", "position": "PG", "careerGames": 750, "careerPPG": 24.3, "draftRound": 1, "allStarAppearances": 8},
    {"name": "Khris Middleton", "position": "SG", "careerGames": 850, "careerPPG": 17.5, "draftRound": 1, "allStarAppearances": 3},
    {"name": "Brook Lopez", "position": "C", "careerGames": 900, "careerPPG": 15.5, "draftRound": 1, "allStarAppearances": 2},
    {"name": "Kareem Abdul-Jabbar", "position": "C", "careerGames": 600, "careerPPG": 28.9, "draftRound": 1, "allStarAppearances": 19},
    {"name": "Ray Allen", "position": "SG", "careerGames": 500, "careerPPG": 19.8, "draftRound": 1, "allStarAppearances": 10},
    {"name": "Sidney Moncrief", "position": "SF", "careerGames": 834, "careerPPG": 15.6, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Bob Dandridge", "position": "SF", "careerGames": 839, "careerPPG": 18.6, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Dave Cowens", "position": "C", "careerGames": 350, "careerPPG": 14.2, "draftRound": 1, "allStarAppearances": 7},
    {"name": "Jrue Holiday", "position": "PG", "careerGames": 1100, "careerPPG": 12.1, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Marques Johnson", "position": "SF", "careerGames": 807, "careerPPG": 20.1, "draftRound": 1, "allStarAppearances": 5}
  ],
  "Minnesota Timberwolves": [
    {"name": "Anthony Edwards", "position": "SG", "careerGames": 350, "careerPPG": 23.5, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Karl-Anthony Towns", "position": "C", "careerGames": 700, "careerPPG": 21.8, "draftRound": 1, "allStarAppearances": 3},
    {"name": "D'Angelo Russell", "position": "PG", "careerGames": 700, "careerPPG": 17.4, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Kevin Garnett", "position": "PF", "careerGames": 1116, "careerPPG": 18.9, "draftRound": 1, "allStarAppearances": 15},
    {"name": "Kevin Love", "position": "C", "careerGames": 700, "careerPPG": 19.2, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Stephon Marbury", "position": "PG", "careerGames": 644, "careerPPG": 19.2, "draftRound": 1, "allStarAppearances": 3},
    {"name": "Latrell Sprewell", "position": "SG", "careerGames": 800, "careerPPG": 18.3, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Terrell Brandon", "position": "PG", "careerGames": 713, "careerPPG": 12.0, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Isiah Rider", "position": "SG", "careerGames": 603, "careerPPG": 17.0, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Wally Szczerbiak", "position": "SF", "careerGames": 800, "careerPPG": 15.2, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Nikola Pekovic", "position": "C", "careerGames": 600, "careerPPG": 13.8, "draftRound": 1, "allStarAppearances": 0}
  ],
  "New Orleans Pelicans": [
    {"name": "Zion Williamson", "position": "PF", "careerGames": 300, "careerPPG": 23.5, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Brandon Ingram", "position": "SF", "careerGames": 500, "careerPPG": 22.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "CJ McCollum", "position": "SG", "careerGames": 650, "careerPPG": 20.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Anthony Davis", "position": "C", "careerGames": 600, "careerPPG": 28.3, "draftRound": 1, "allStarAppearances": 8},
    {"name": "Chris Paul", "position": "PG", "careerGames": 450, "careerPPG": 17.2, "draftRound": 1, "allStarAppearances": 11},
    {"name": "David West", "position": "C", "careerGames": 800, "careerPPG": 15.6, "draftRound": 1, "allStarAppearances": 2},
    {"name": "Pete Maravich", "position": "PG", "careerGames": 658, "careerPPG": 24.2, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Daniel Theis", "position": "C", "careerGames": 650, "careerPPG": 9.2, "draftRound": 2, "allStarAppearances": 0},
    {"name": "Jose CalderÃ³n", "position": "PG", "careerGames": 900, "careerPPG": 10.1, "draftRound": 2, "allStarAppearances": 0}
  ],
  "New York Knicks": [
    {"name": "Julius Randle", "position": "PF", "careerGames": 800, "careerPPG": 21.1, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Jalen Brunson", "position": "PG", "careerGames": 300, "careerPPG": 24.2, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Mikal Bridges", "position": "SF", "careerGames": 300, "careerPPG": 18.6, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Walt Frazier", "position": "PG", "careerGames": 825, "careerPPG": 18.9, "draftRound": 1, "allStarAppearances": 7},
    {"name": "Willis Reed", "position": "C", "careerGames": 650, "careerPPG": 18.7, "draftRound": 1, "allStarAppearances": 8},
    {"name": "Earl Monroe", "position": "SG", "careerGames": 926, "careerPPG": 17.8, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Patrick Ewing", "position": "C", "careerGames": 1183, "careerPPG": 24.3, "draftRound": 1, "allStarAppearances": 12},
    {"name": "John Starks", "position": "SG", "careerGames": 940, "careerPPG": 12.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Charles Oakley", "position": "PF", "careerGames": 1159, "careerPPG": 10.7, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Mark Jackson", "position": "PG", "careerGames": 1083, "careerPPG": 12.2, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Bernard King", "position": "SF", "careerGames": 880, "careerPPG": 22.5, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Dave DeBusschere", "position": "PF", "careerGames": 875, "careerPPG": 16.1, "draftRound": 1, "allStarAppearances": 6}
  ],
  "Oklahoma City Thunder": [
    {"name": "Shai Gilgeous-Alexander", "position": "PG", "careerGames": 400, "careerPPG": 28.1, "draftRound": 1, "allStarAppearances": 2},
    {"name": "Jalen Williams", "position": "SF", "careerGames": 250, "careerPPG": 22.5, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Luguentz Dort", "position": "SF", "careerGames": 400, "careerPPG": 16.1, "draftRound": 2, "allStarAppearances": 0},
    {"name": "Kevin Durant", "position": "SF", "careerGames": 1300, "careerPPG": 27.1, "draftRound": 1, "allStarAppearances": 13},
    {"name": "Russell Westbrook", "position": "PG", "careerGames": 1200, "careerPPG": 23.2, "draftRound": 1, "allStarAppearances": 9},
    {"name": "James Harden", "position": "SG", "careerGames": 600, "careerPPG": 23.8, "draftRound": 1, "allStarAppearances": 11},
    {"name": "Serge Ibaka", "position": "C", "careerGames": 1000, "careerPPG": 12.6, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Gary Payton", "position": "PG", "careerGames": 300, "careerPPG": 19.3, "draftRound": 1, "allStarAppearances": 9},
    {"name": "Shawn Kemp", "position": "PF", "careerGames": 800, "careerPPG": 14.6, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Ray Allen", "position": "SG", "careerGames": 400, "careerPPG": 22.1, "draftRound": 1, "allStarAppearances": 10}
  ],
  "Orlando Magic": [
    {"name": "Paolo Banchero", "position": "SF", "careerGames": 250, "careerPPG": 23.2, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Jalen Suggs", "position": "PG", "careerGames": 300, "careerPPG": 12.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Shaquille O'Neal", "position": "C", "careerGames": 443, "careerPPG": 28.0, "draftRound": 1, "allStarAppearances": 15},
    {"name": "Anfernee Hardaway", "position": "SG", "careerGames": 726, "careerPPG": 21.7, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Dwight Howard", "position": "C", "careerGames": 747, "careerPPG": 18.3, "draftRound": 1, "allStarAppearances": 8},
    {"name": "Nikola Vucevic", "position": "C", "careerGames": 600, "careerPPG": 15.7, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Penny Hardaway", "position": "SG", "careerGames": 500, "careerPPG": 20.2, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Nick Anderson", "position": "SF", "careerGames": 1000, "careerPPG": 15.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Dennis Scott", "position": "SF", "careerGames": 820, "careerPPG": 12.7, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Hedo Turkoglu", "position": "SF", "careerGames": 900, "careerPPG": 11.4, "draftRound": 1, "allStarAppearances": 0}
  ],
  "Philadelphia 76ers": [
    {"name": "Joel Embiid", "position": "C", "careerGames": 650, "careerPPG": 28.4, "draftRound": 1, "allStarAppearances": 7},
    {"name": "Tyrese Maxey", "position": "PG", "careerGames": 350, "careerPPG": 22.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Wilt Chamberlain", "position": "C", "careerGames": 490, "careerPPG": 30.1, "draftRound": 1, "allStarAppearances": 13},
    {"name": "Moses Malone", "position": "C", "careerGames": 650, "careerPPG": 24.6, "draftRound": 1, "allStarAppearances": 12},
    {"name": "Julius Erving", "position": "SF", "careerGames": 836, "careerPPG": 24.2, "draftRound": 1, "allStarAppearances": 11},
    {"name": "Allen Iverson", "position": "PG", "careerGames": 996, "careerPPG": 26.7, "draftRound": 1, "allStarAppearances": 11},
    {"name": "Charles Barkley", "position": "PF", "careerGames": 800, "careerPPG": 23.0, "draftRound": 1, "allStarAppearances": 11},
    {"name": "Maurice Cheeks", "position": "PG", "careerGames": 1101, "careerPPG": 9.8, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Bobby Jones", "position": "SF", "careerGames": 842, "careerPPG": 10.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Reggie Jackson", "position": "PG", "careerGames": 350, "careerPPG": 13.2, "draftRound": 1, "allStarAppearances": 0}
  ],
  "Phoenix Suns": [
    {"name": "Kevin Durant", "position": "SF", "careerGames": 500, "careerPPG": 29.1, "draftRound": 1, "allStarAppearances": 13},
    {"name": "Devin Booker", "position": "SG", "careerGames": 700, "careerPPG": 26.3, "draftRound": 1, "allStarAppearances": 8},
    {"name": "Chris Paul", "position": "PG", "careerGames": 600, "careerPPG": 18.5, "draftRound": 1, "allStarAppearances": 11},
    {"name": "Charles Barkley", "position": "PF", "careerGames": 736, "careerPPG": 23.4, "draftRound": 1, "allStarAppearances": 11},
    {"name": "Dan Majerle", "position": "SG", "careerGames": 500, "careerPPG": 11.2, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Steve Nash", "position": "PG", "careerGames": 600, "careerPPG": 15.6, "draftRound": 1, "allStarAppearances": 8},
    {"name": "Amar'e Stoudemire", "position": "PF", "careerGames": 800, "careerPPG": 18.8, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Shawn Marion", "position": "SF", "careerGames": 900, "careerPPG": 15.8, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Devin Harris", "position": "PG", "careerGames": 250, "careerPPG": 11.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Tom Chambers", "position": "SF", "careerGames": 1104, "careerPPG": 17.9, "draftRound": 1, "allStarAppearances": 1}
  ],
  "Portland Trail Blazers": [
    {"name": "Damian Lillard", "position": "PG", "careerGames": 700, "careerPPG": 25.3, "draftRound": 1, "allStarAppearances": 8},
    {"name": "CJ McCollum", "position": "SG", "careerGames": 600, "careerPPG": 21.4, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Bill Walton", "position": "C", "careerGames": 468, "careerPPG": 13.3, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Clyde Drexler", "position": "SG", "careerGames": 1086, "careerPPG": 20.4, "draftRound": 1, "allStarAppearances": 10},
    {"name": "Maurice Lucas", "position": "PF", "careerGames": 1000, "careerPPG": 14.6, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Brandon Roy", "position": "SG", "careerGames": 372, "careerPPG": 19.2, "draftRound": 1, "allStarAppearances": 1},
    {"name": "LaMarcus Aldridge", "position": "PF", "careerGames": 700, "careerPPG": 19.4, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Scottie Pippen", "position": "SF", "careerGames": 150, "careerPPG": 10.8, "draftRound": 1, "allStarAppearances": 8},
    {"name": "Sam Bowie", "position": "C", "careerGames": 511, "careerPPG": 10.9, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Terry Porter", "position": "PG", "careerGames": 1274, "careerPPG": 9.0, "draftRound": 1, "allStarAppearances": 0}
  ],
  "Sacramento Kings": [
    {"name": "De'Aaron Fox", "position": "PG", "careerGames": 450, "careerPPG": 25.8, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Domantas Sabonis", "position": "C", "careerGames": 400, "careerPPG": 20.5, "draftRound": 1, "allStarAppearances": 2},
    {"name": "Buddy Hield", "position": "SG", "careerGames": 550, "careerPPG": 13.5, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Oscar Robertson", "position": "PG", "careerGames": 600, "careerPPG": 25.0, "draftRound": 1, "allStarAppearances": 12},
    {"name": "Nate Archibald", "position": "PG", "careerGames": 876, "careerPPG": 16.4, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Jerry West", "position": "SG", "careerGames": 332, "careerPPG": 27.2, "draftRound": 1, "allStarAppearances": 14},
    {"name": "Vlade Divac", "position": "C", "careerGames": 1134, "careerPPG": 13.9, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Peja Stojakovic", "position": "SF", "careerGames": 951, "careerPPG": 15.5, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Mike Bibby", "position": "PG", "careerGames": 1000, "careerPPG": 14.3, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Chris Webber", "position": "C", "careerGames": 700, "careerPPG": 20.1, "draftRound": 1, "allStarAppearances": 5}
  ],
  "San Antonio Spurs": [
    {"name": "Tim Duncan", "position": "PF", "careerGames": 1393, "careerPPG": 19.0, "draftRound": 1, "allStarAppearances": 15},
    {"name": "Tony Parker", "position": "PG", "careerGames": 1254, "careerPPG": 15.5, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Manu Ginobili", "position": "SG", "careerGames": 1057, "careerPPG": 13.3, "draftRound": 1, "allStarAppearances": 2},
    {"name": "Kawhi Leonard", "position": "SF", "careerGames": 300, "careerPPG": 18.9, "draftRound": 1, "allStarAppearances": 6},
    {"name": "George Hill", "position": "PG", "careerGames": 1000, "careerPPG": 9.6, "draftRound": 1, "allStarAppearances": 0},
    {"name": "David Robinson", "position": "C", "careerGames": 987, "careerPPG": 21.1, "draftRound": 1, "allStarAppearances": 10},
    {"name": "DeMar DeRozan", "position": "SG", "careerGames": 500, "careerPPG": 20.8, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Derrick White", "position": "PG", "careerGames": 400, "careerPPG": 10.1, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Sean Elliott", "position": "SF", "careerGames": 884, "careerPPG": 13.7, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Patty Mills", "position": "PG", "careerGames": 900, "careerPPG": 10.1, "draftRound": 2, "allStarAppearances": 0}
  ],
  "Toronto Raptors": [
    {"name": "DeMar DeRozan", "position": "SG", "careerGames": 400, "careerPPG": 21.3, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Pascal Siakam", "position": "PF", "careerGames": 500, "careerPPG": 16.5, "draftRound": 1, "allStarAppearances": 1},
    {"name": "Scottie Barnes", "position": "SF", "careerGames": 350, "careerPPG": 15.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Kawhi Leonard", "position": "SF", "careerGames": 60, "careerPPG": 26.6, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Kyle Lowry", "position": "PG", "careerGames": 850, "careerPPG": 14.1, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Marc Gasol", "position": "C", "careerGames": 350, "careerPPG": 12.6, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Serge Ibaka", "position": "C", "careerGames": 400, "careerPPG": 12.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Vince Carter", "position": "SG", "careerGames": 300, "careerPPG": 20.1, "draftRound": 1, "allStarAppearances": 8},
    {"name": "Jamal Murray", "position": "PG", "careerGames": 150, "careerPPG": 19.8, "draftRound": 1, "allStarAppearances": 2},
    {"name": "O.G. Anunoby", "position": "SF", "careerGames": 400, "careerPPG": 11.2, "draftRound": 1, "allStarAppearances": 0}
  ],
  "Utah Jazz": [
    {"name": "Donovan Mitchell", "position": "SG", "careerGames": 650, "careerPPG": 24.1, "draftRound": 1, "allStarAppearances": 3},
    {"name": "Rudy Gobert", "position": "C", "careerGames": 900, "careerPPG": 13.5, "draftRound": 1, "allStarAppearances": 1},
    {"name": "John Stockton", "position": "PG", "careerGames": 1504, "careerPPG": 13.1, "draftRound": 1, "allStarAppearances": 10},
    {"name": "Karl Malone", "position": "PF", "careerGames": 1476, "careerPPG": 25.0, "draftRound": 1, "allStarAppearances": 14},
    {"name": "Mark Eaton", "position": "C", "careerGames": 875, "careerPPG": 5.4, "draftRound": 1, "allStarAppearances": 2},
    {"name": "Thurl Bailey", "position": "PF", "careerGames": 1087, "careerPPG": 11.6, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Adrian Dantley", "position": "SF", "careerGames": 955, "careerPPG": 24.3, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Jeff Hornacek", "position": "SG", "careerGames": 1085, "careerPPG": 14.5, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Byron Russell", "position": "SF", "careerGames": 900, "careerPPG": 10.8, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Bojan Bogdanovic", "position": "SF", "careerGames": 650, "careerPPG": 17.2, "draftRound": 1, "allStarAppearances": 1}
  ],
  "Washington Wizards": [
    {"name": "Bradley Beal", "position": "SG", "careerGames": 900, "careerPPG": 23.2, "draftRound": 1, "allStarAppearances": 6},
    {"name": "Kristaps Porzingis", "position": "C", "careerGames": 400, "careerPPG": 21.4, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Wes Unseld", "position": "C", "careerGames": 984, "careerPPG": 10.8, "draftRound": 1, "allStarAppearances": 5},
    {"name": "Elvin Hayes", "position": "C", "careerGames": 1303, "careerPPG": 21.0, "draftRound": 1, "allStarAppearances": 12},
    {"name": "Gilbert Arenas", "position": "PG", "careerGames": 716, "careerPPG": 20.7, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Caron Butler", "position": "SF", "careerGames": 1200, "careerPPG": 14.1, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Juan Dixon", "position": "SG", "careerGames": 900, "careerPPG": 13.5, "draftRound": 1, "allStarAppearances": 0},
    {"name": "Antawn Jamison", "position": "PF", "careerGames": 1100, "careerPPG": 18.3, "draftRound": 1, "allStarAppearances": 4},
    {"name": "Rip Hamilton", "position": "SG", "careerGames": 350, "careerPPG": 16.2, "draftRound": 1, "allStarAppearances": 0},
    {"name": "John Wall", "position": "PG", "careerGames": 600, "careerPPG": 18.5, "draftRound": 1, "allStarAppearances": 5}
  ]
}

